spring:
  application:
    name: sytk-booking
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
