spring:
  application:
    name: sytk-read
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
